#ifndef STDTYPES_H
#define STDTYPES_H

#ifndef uint8_t
#define uint8_t unsigned char
#endif

#define MAX_MOVE_SEQUENCE 20
#define MAX_BUTTON 12
#define MAX_MOTOR 12
#define MAX_COMMAND_LENGTH 256
#define MAX_PARAMS_CHESSBOARD 4


#ifndef PI
#define PI M_1_PI
#endif

typedef enum {
    MOTOR_INIT,
    MOTOR_EXECUTE_INCREASE_SPEED,
    MOTOR_EXECUTE_CRUISE_SPEED,
    MOTOR_EXECUTE_DECREASE_SPEED,
    MOTOR_EXECUTE_HOME,
    MOTOR_DONE
}MOTOR_CONTROL_STATE;

typedef enum {
    MOTOR_LIMIT_MIN,
    MOTOR_LIMIT_MAX,
}MOTOR_LIMIT_TYPE;

typedef enum{
    ROBOT_INIT,
    ROBOT_EXECUTE_GO_HOME,
    ROBOT_EXECUTE_POSITION,
    ROBOT_EXECUTE_SEQUENCE,
    ROBOT_EXECUTE_DONE,
}ROBOT_STATE;

typedef enum{
    ROBOT_MOVE_INIT,
    ROBOT_MOVE_EXECUTE,
    ROBOT_MOVE_CAPTURE,
    ROBOT_MOVE_DONE,
}ROBOT_SEQUENCE_STATE;

typedef enum {
    MACHINE_INIT,
    MACHINE_WAIT_COMMAND,
    MACHINE_EXECUTE_COMMAND,
    MACHINE_EXECUTE_COMMAND_DONE,
}MACHINE_STATE;

typedef enum {
    MOTION_JOINT_SPACE,
    MOTION_CARTESION_SPACE,
}MOTION_SPACES;

#endif // STDTYPES_H
